[package]
name = "maplestory"
version = "0.1.1"
edition = "2024"
description = "maplestory"
repository = "https://github.com/psvm203/maplestory"
license = "MIT"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
